# Manual
title: 呓语梦轩

# support language
language:
  - zh-Hans

########## The following are optional #########
# author name in footer
author: your name
# author name link in footer
website: /

#favicon, replaceable
favicon: /ico.webp

# 可选
links:
  # github 图标 的链接，换成你自己的，配置时带上 http、https或者//
  github: https://github.com/awaae001
  # 普通链接，可配置多个，以下是示例
  custom:
    - name: 友人帐
      URL: /link

    - name: 说说
      URL: /daily

    - name: 十年之约
      URL: /box

# 可选, giscus 评论系统
# 这里配置 https://giscus.app/zh-CN，将生成好的填在下面
# enable 为 true 时， 填自己的 repo、repo_id、category_id
giscus:
  enable: false
  repo: "awaae001/awaae001.github.io"
  repo_id: "R_kgDOJrn4SA"
  category_id: "DIC_kwDOJrn4SM4CZL0n"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "top"
  theme: "preferred_color_scheme"
  lang: "zh-CN"

# 可选, valine
valine:
  # 评论
  enableComment: false
  # 阅读量
  enableCounter: false
  # valine appID
  appID: HLL0twzTQliUf6VA2pJLr7PF-MdYXbMMI
  # valine appKey
  appKey: ncEqAdUCrIeowlmVsW4zrA4V
  placeholder: 来吧！
  avatar: retro

# 可选 waline评论系统
#https://waline.js.org/
#是上面的valine的有服务器后端版本，在现在的环境下可用。
waline:
  #评论系统开关
  enableComment: false
  #服务器地址
  serverURL: api.m-c.top
  #表情回应
  reaction: true

artalk:
  enableComment: true
  enable: 呓语梦轩
  server: https://talk.m-c.top


# 是否开启“不蒜子”统计访问量，可选
busuanzi: false

# 底部版权开始年份，不配置默认为今年
siteStartYear: 2022

####### 站外搜索配置 #####
# 站点如果【被搜索引擎收录】，可以配置通过搜索引擎全站搜索
# searchEngine：搜索引擎，不配置则默认为谷歌，可替换为百度等其他搜索引擎的搜索 URL
#searchEngine: https://www.baidu.com/s?wd=
searchEngine: https://www.google.com/search?q=
# homeHost：要搜索的站点域名，不配置默认取当前页面的域名，以下是示例
homeHost: blog.awaae001.top

#设置为 true 之前，要先确保，已经创建了 hexo 的 tags\categories\about 页面
tags: false
categories: false
about: false

# 左侧导航栏，用文件名还是文章名
sidebar:
  # usePostTitle 为 ture 用文章名，不填或为 false 用文件名
  usePostTitle: ture

# 其他配置项...



#页面背景图片
blogBackgroundImage: "https://pic.awaae001.top/ai1_178504_e25aaeb4.webp"
blogBackgroundSize: "cover" # 你可以根据需要选择 'cover', 'contain' 或其他值
blurAmount: 10px # 可以在这里设置模糊值

#页面底部的网站运行时长,注意：时间格式为 年-月-日，单数必须要要加零
custom:
  enableRuntimeCard: ture
  siteStartDate: "2023-05-27"
  siteword: 本站已运行

#一个有问题无法再配置文件更改的功能
#share:
#  button: ture
#  time: 1000

postFooter:
  div: ture
  likewordA: 赞助我！
  yaofan: 啊，没钱了，谁来帮帮我啊
  shareword: 分享啊！
  QrcodeA: https://image.m-c.top/?/images/2024/01/30/dJuwI48Rry/alipay.jpg
  QrcodeB: https://image.m-c.top/?/images/2024/01/30/OPzAQTymjZ/weixin.png

#甜莉GPT
tianligpt:
  enableComment: ture
  key: vgJgWKgS0Va