name: dev

on:
  push:
    branches:
      - mian

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKViOfdpFOhCIes5WSle08u3yHB3uRUOsssRynGDhDTKmFi930upOw34gS/eC7XhBFB13TqAILdu+XplWpdsROowjXChH4N41DdADI6Z1FIrrxyNMBDZiZ3F3dg8h7GZL0fbRqEFC0D8fEygHudatCFvxDr8ZMdrg9xvoafw2HNWzrjG6fvtBOXrOI9fWha7jBs2wXg0l+HLgLchFcbwnNoKfz75GhNLeIFVXMn4mX0Eac+v+3pT1xf7qKT3X5rcvYVgTFLpgfR9ncEbD41PYzSlWffil9UAOtbeZt0KecmQRVExOxKTQ6ljrB1Sc7gsDHxKHmy39xw2nzuVpu6wY50C8WeF4dvciW///B7+ne+32fQ1zWr7UmFIIk5hKuNwi8E7dFyT33YOTykRBB5jXIWBbbgROM25bhiqAzSywXb9n39LZOVQp1xuXHMrCa+2CW9UlnSD59Quph1W/bWixV5C12eLx9pw2ZqxqJiFvkz5ipoSIktSPGcrTUs7v6+9MmTKRUeg7mqa93F1Tg4YGWA/ny8h1Fq3FZOIehcP2qkMbqqqBvRxmxQXu9Ls7EZ3HlhH098IrQ6/SyjNj0cG2pOwdU9CwAI7z3gQmeaTQTR0U7ALipJg14fcx/OVuF7eW2jo1tdT2tyDETIiPcCSxd7iiEU0WQWnzpGMqDKpcXIQ== Hexo Deploy Key
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "3271436144@qq.com"
          git config --global user.name "awaae001"
          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy
